from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    accuracy_score,
    classification_report,
    confusion_matrix,
)
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

def main() -> None:
    """Train and evaluate a KNN classifier using the Iris dataset."""

    #Load the Iris dataset
    iris=load_iris()

    # X contains the four flower measurements
    X=pd.DataFrame(
        iris.data,
        columns=iris.feature_names,
    )

    # y contains the correct flower species codes
    y=pd.Series(
        iris.target,
        name="species_code",
    )

    # Create a readable copy of the dataset for inspection.
    dataframe=X.copy()
    dataframe["species_code"]= y 
    dataframe["species_name"]=dataframe["species_code"].map(
        dict(enumerate(iris.target_names)) 
        # enumerate() gives a unique number to each iris.target_names
        # dict() constructs a dictionary(key-to-value) with the numeric code pairs generated by enumerate
        # .map() writes the dictionary according to the dictionary into the dataframe respectively
    )
    
    # Understand the dataset
    print("=" * 60)
    print("IRIS DATASET OVERVIEW")
    print("=" * 60)
    print("\n First five rows:")
    print(dataframe.head())

    print("\nDataset dimensions:")
    print(dataframe.shape)

    print("\nFeature names:")
    for feature_name in iris.feature_names:
        print(f"- {feature_name}")

    print("\nTarget classes:")
    for class_number, class_name in enumerate(iris.target_names):
        print(f"{class_number} = {class_name}")

    print("\nNumber of samples in each class:")
    print(dataframe["species_name"].value_counts())

    print("\nMissing values:")
    print(dataframe.isnull().sum())

    print("\nNumerical summary:")
    print(dataframe.describe())

    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.20,
        random_state=42,
        stratify=y,
    )

    print("\nTraining feature shape:", X_train.shape)
    print("Testing feature shape:", X_test.shape)
    print("Training target shape:", y_train.shape)
    print("Testing target shape:", y_test.shape)

    # Scale the features
    scaler = StandardScaler()

    # Fit the scaler only on training data to avoid data leakage.
    X_train_scaled = scaler.fit_transform(X_train)

    # Transform the testing data using the training scaler.
    X_test_scaled = scaler.transform(X_test)

    # Create and train the KNN model
    model = KNeighborsClassifier(n_neighbors=5)

    model.fit(
        X_train_scaled,
        y_train,
    )

    # Make predictions
    predictions = model.predict(X_test_scaled)

    comparison = pd.DataFrame(
        {
            "Actual": iris.target_names[y_test.to_numpy()],
            "Predicted": iris.target_names[predictions],
        }
    )

    print("\nActual versus predicted classes:")
    print(comparison.to_string(index=False))

    # Evaluate the model
    accuracy = accuracy_score(
        y_test,
        predictions,
    )

    matrix = confusion_matrix(
        y_test,
        predictions,
    )

    print("\nModel accuracy:")
    print(f"{accuracy:.4f}")
    print(f"{accuracy * 100:.2f}%")

    print("\nConfusion matrix:")
    print(matrix)

    print("\nClassification report:")
    print(
        classification_report(
            y_test,
            predictions,
            target_names=iris.target_names,
            digits=4,
        )
    )

    # Create and save the confusion matrix chart
    results_directory = Path("results")
    results_directory.mkdir(exist_ok=True)

    display = ConfusionMatrixDisplay(
        confusion_matrix=matrix,
        display_labels=iris.target_names,
    )

    display.plot()
    plt.title("KNN Confusion Matrix - Iris Dataset")
    plt.tight_layout()

    chart_path = results_directory / "confusion_matrix.png"

    plt.savefig(
        chart_path,
        dpi=300,
        bbox_inches="tight",
    )

    print(f"\nConfusion matrix chart saved to: {chart_path}")

    plt.show()

    # Test the model with one new flower
    new_flower = pd.DataFrame(
        [[5.1, 3.5, 1.4, 0.2]],
        columns=iris.feature_names,
    )

    new_flower_scaled = scaler.transform(new_flower)

    new_prediction = model.predict(new_flower_scaled)

    predicted_species = iris.target_names[new_prediction[0]]

    print("\nNew flower measurements:")
    print(new_flower.to_string(index=False))

    print("\nPredicted species:")
    print(predicted_species)


if __name__ == "__main__":
    main()